papers:
  '[6] (**First Author**, preparing for submission). Zhihua Zhong, Hideki Takayasu, Misako Takayasu. Renormalization method on human mobility resulted in scale invariance and a new type of gravity relation based on RECM':
    ''
  '[5] (**First Author**). Zhong, Z., Takayasu, H. & Takayasu, M. Human mobility description by physical analogy of electric circuit network based on GPS data. Sci Rep 14, 13380 (2024).':
    'https://www.nature.com/articles/s41598-024-63719-z'
  '[4] (**Co-first Author**). Gao M*, Zhong Z*, Yue Y, Liu F. Correlation between glycaemic variability and prognosis in diabetic patients with CKD. Endokrynol Pol. 73(6):947-953 (2022).':
    'https://journals.viamedica.pl/endokrynologia_polska/article/view/EP.a2022.0092/70385'
  '[3] (**Co-first Author**). Liu, S*, Zhong, Z* & Liu, F. Prognostic value of hyperuricemia for patients with sepsis in the intensive care unit [J]. Sci Rep 12, 1070 (2022).':
    'https://www.nature.com/articles/s41598-022-04862-3'
  '[2] (**Co-first Author**). Huang Y*, Zhong Z*, Liu F. The Association of Coagulation Indicators and Coagulant Agents With 30-Day Mortality of Critical Diabetics [J]. Clin Appl Thromb Hemost. 27:10760296211026385 (2021 Jan-Dec).':
    'https://journals.sagepub.com/doi/full/10.1177/10760296211026385'
  '[1] (**First Author**). Zhong, Z., Yuan, X., Liu, S. et al. Machine learning prediction models for prognosis of critically ill patients after open-heart surgery [J]. Sci Rep 11, 3384 (2021).':
    'https://www.nature.com/articles/s41598-021-83020-7'

presentation:
  '[6, coming]':
    'Renormalization method for human flow based on electric circuit model, Physical Society of Japan (2024/9).'
  '[5]':
    'Novel approaches to human mobility: human mobility description by a physical analogy of electric circuit network based on GPS data, The 37th Annual Conference of the Japanese Society for Artificial Intelligence (2024/5).'
  '[4]':
    'Electric circuit network and application in the human mobility problems-part-2, The 86th National Convention of Information Processing Socity of Japan (IPSJ) (2024/3).'
  '[3]':
    'Electric circuit network and application in the human mobility problems-part-1, Network Science 2023 (2023/12)'
  '[2]':
    'Electric circuit network description of urban human mobility based on GPS data, Physical Society of Japan (2023/9).'
  '[1]':
    'An analysis of human flow pattern based on Revised Electric Circuit Model, Statphys28 (2023/8).'

grant_award_qualification:
  '[Grant-1]':
    'Japan Society for the Promotion of Science (JSPS) Research Fellowship for Young Scientists DC2 (Grant Number JP24KJ1060; from 2024/4 to 2026/4, Doctor, Japan)'
  '[Grant-2]':
    'Support for Pioneering Research Initiated by the Next Generation by Japan Science and Technology Agency (Grant Number JPMJSP2106; from 2022/9 to 2024/4, Doctor, Japan)'
  '[Award-1]':
    '[Software Copyright (2021, Master, China)](https://github.com/Zhihua-Zhong/Achievement-Galary/blob/main/Software%20Copyright%20(2021%2C%20Master).pdf)'
  '[Award-2]':
    '[China National Scholarship for graduate students (2021, Master, China)](https://github.com/Zhihua-Zhong/Achievement-Galary/blob/main/National%20Scholarship%20Certificate%20(2021%2C%20Master).pdf)'
  '[Certificate-1]':
    'TOEIC (English ability): 810/1000 (2021, Master)'
  '[Certificate-2]':
    'JLPT N1 (Japanese ability): 140/180 (2021, Master)'
