papers:
  '[6, corresponding, under peer review]. Feasibility discussion of quantum cryptography for Internet of Things security: A literature review': 
    ''
  '[5, first, under peer review]. Zhong Zhihua, Hideki Takayasu, Misako Takayasu. Novel approaches to urban science problems: human mobility description by physical analogy of electric circuit network based on GPS data':
    ''
  '[4, co-first]. Gao M*, Zhong Z*, Yue Y, Liu F. Correlation between glycaemic variability and prognosis in diabetic patients with CKD. Endokrynol Pol. 73(6):947-953 (2022).':
    'https://journals.viamedica.pl/endokrynologia_polska/article/view/EP.a2022.0092/70385'
  '[3, co-first]. Liu, S*, Zhong, Z* & Liu, F. Prognostic value of hyperuricemia for patients with sepsis in the intensive care unit [J]. Sci Rep 12, 1070 (2022).':
    'https://www.nature.com/articles/s41598-022-04862-3'
  '[2, co-first]. Huang Y*, Zhong Z*, Liu F. The Association of Coagulation Indicators and Coagulant Agents With 30-Day Mortality of Critical Diabetics [J]. Clin Appl Thromb Hemost. 27:10760296211026385 (2021 Jan-Dec).':
    'https://journals.sagepub.com/doi/full/10.1177/10760296211026385'
  '[1, first]. Zhong, Z., Yuan, X., Liu, S. et al. Machine learning prediction models for prognosis of critically ill patients after open-heart surgery [J]. Sci Rep 11, 3384 (2021).':
    'https://www.nature.com/articles/s41598-021-83020-7'

presentation:
  '[5]':
    'Novel approaches to human mobility: human mobility description by a physical analogy of electric circuit network based on GPS data, The 37th Annual Conference of the Japanese Society for Artificial Intelligence (2023/5).'
  '[4]':
    'Novel approaches to urban human mobility: a physical analogy of electric circuit network and resulting gravity relations based on GPS data, The 86th National Convention of IPSJ (2024/3).'
  '[3]':
    'Electric circuit network and application in the human mobility problems, Network Science 2023 (2023/12)'
  '[2]':
    'Electric circuit network description of urban human mobility based on GPS data, Physical Society of Japan (2023/9).'
  '[1]':
    'An analysis of human flow pattern based on Revised Electric Circuit Model, Statphys28 (2023/8).'

grant_award_qualification:
  '[Grant-1]':
    'JSPS (Japan Society for the Promotion of Science) Research Fellowship for Young Scientists (from 2024/4 to 2026/4, Doctor, Japan)'
  '[Grant-2]':
    'Support for Pioneering Research Initiated by the Next Generation by Japan Science and Technology Agency (Grant Number JPMJSP2106; from 2022/9 to 2024/4, Doctor, Japan)'
  '[Award-1]':
    'Software Copyright (2021, Master, China)'
  '[Award-2]':
    'China National Scholarship for graduate students (2021, Master, China)'
  '[Certificate-1]':
    'TOEIC (English ability): 810/1000 (2021, Master)'
  '[Certificate-2]':
    'JLPT N1 (Japanese ability): 140/180 (2021, Master)'
