name:
  'Zhihua Zhong \n 
  (鍾　志華)'

description:
  'Doctoral student at ***Tokyo Institude of Technology*** \n 
  Japan Society for the Promotion of Science (JSPS, DC2) 日本学術振興特別研究員 \n 
  Major: School of Computing, Artificial Intelligence \n 
  Main direction: Algorithm, Optimization modelling'

email:
  'zhong.z.af@m.titech.ac.jp'

social_media:
  'My Github':
    'https://github.com/Zhihua-Zhong'
  'My Laboratory':
    'http://www.smp.dis.titech.ac.jp/en/'
  'My ORCID':
    'https://orcid.org/0009-0003-6636-8203'
